swagger: "2.0"
info:
  description: This is the swagger file that goes with the server code
  version: "1.0.0"
  title: Swagger REST API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: /api

# Paths supported by the server application
paths:
  /reports:
    get:
      operationId: reports.read_all_reports
      tags:
        - Reports
      summary: Gets all users and data by month.
      description: Returns all users and all data collected in reports.
      responses:
        200:
          description: Reports response
          schema:
            type: array
            items:
              properties:
                employeeName:
                  type: string
                data:
                  type: object
                  items: {}

  /reports/{lname}:
    get:
      operationId: reports.read_one_report
      tags:
        - Reports
      summary: Read one report
      description: Read report of last name
      parameters:
        - name: lname
          in: path
          description: Last name of the person to get from the reports
          type: string
          required: True
      responses:
        200:
          description: Found person in reports list
          schema:
            type: array
            items:
              properties:
                employeeName:
                  type: string
                annual_leave:
                  type: object
                  items: {}
